# Merged on top of Core-Styles base config
# SEE: https://github.com/tacc-wbomar/Core-Styles/blob/test/as-npm-package/.postcssrc.base.yml
plugins:
  postcss-import:
    path:
      - 'node_modules/tacc-core-styles/source'
  postcss-env-function:
    importFrom:
      - 'node_modules/tacc-core-styles/source/_themes/export.js'
