# Merged on top of Core-Styles base config
# SEE: https://github.com/tacc-wbomar/Core-Styles/blob/main/.postcssrc.base.yml
plugins:
  postcss-import:
    path:
      - '_shared/static/css/src'
      - 'node_modules/core-styles/source'
  postcss-env-function:
    importFrom:
      - 'node_modules/core-styles/source/_themes/default.json'
