# Merged on top of TACC/Core-CMS base config
# SEE: https://github.com/TACC/Core-CMS-Resources/blob/main/taccsite_cms/static/site_cms/css/.postcssrc.yml
plugins:
  postcss-env-function:
    importFrom:
      - 'node_modules/@tacc/core-styles/source/_themes/has-dark-logo.json'
